# Generated by Django 5.2 on 2025-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0002_complaint_address_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
