# Generated by Django 5.2 on 2025-05-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0003_complaint_image_alter_complaint_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='purok',
            field=models.CharField(choices=[('Purok 1 Proper', 'Purok 1 Proper'), ('Purok 1 Don Julio', 'Purok 1 Don Julio'), ('Purok 2 Proper', 'Purok 2 Proper'), ('Purok 2 Don Julio', 'Purok 2 Don Julio'), ('Purok 3 Proper', 'Purok 3 Proper'), ('Purok 3 Don Julio', 'Purok 3 Don Julio'), ('Purok 4 Proper', 'Purok 4 Proper'), ('Purok 4 Don Julio', 'Purok 4 Don Julio'), ('Purok 5 Proper', 'Purok 5 Proper'), ('Purok 5 Don Julio', 'Purok 5 Don Julio'), ('Purok 6', 'Purok 6'), ('Purok 7', 'Purok 7'), ('Purok 8', 'Purok 8'), ('Purok 9', 'Purok 9'), ('Purok Pag-asa', 'Purok Pag-asa'), ('Purok Tower', 'Purok Tower')], max_length=50),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='purok',
            field=models.CharField(choices=[('Purok 1 Proper', 'Purok 1 Proper'), ('Purok 1 Don Julio', 'Purok 1 Don Julio'), ('Purok 2 Proper', 'Purok 2 Proper'), ('Purok 2 Don Julio', 'Purok 2 Don Julio'), ('Purok 3 Proper', 'Purok 3 Proper'), ('Purok 3 Don Julio', 'Purok 3 Don Julio'), ('Purok 4 Proper', 'Purok 4 Proper'), ('Purok 4 Don Julio', 'Purok 4 Don Julio'), ('Purok 5 Proper', 'Purok 5 Proper'), ('Purok 5 Don Julio', 'Purok 5 Don Julio'), ('Purok 6', 'Purok 6'), ('Purok 7', 'Purok 7'), ('Purok 8', 'Purok 8'), ('Purok 9', 'Purok 9'), ('Purok Pag-asa', 'Purok Pag-asa'), ('Purok Tower', 'Purok Tower')], max_length=50),
        ),
    ]
