# Generated by Django 5.2 on 2025-05-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0004_alter_complaint_address_alter_profile_purok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_ACTION', 'In Action'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10),
        ),
    ]
