# Generated by Django 5.2 on 2025-05-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0005_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
