# Generated by Django 5.2.1 on 2025-05-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0006_residentprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
