# Generated by Django 5.2.1 on 2025-05-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0007_residentprofile_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AddField(
            model_name='complaint',
            name='contact_number',
            field=models.CharField(default='Not Provided', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
