# Generated by Django 5.2.1 on 2025-05-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0008_remove_complaint_resident_remove_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_ACTION', 'In Action'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10),
        ),
    ]
